### ISSUE TITLE
Add two users to eks_allowed_k8s_users list

### ISSUE THREAD

**Issue by trallnag** [falcosecurity/plugins#216]
**Motivation**

The rules document [k8s_audit_rules.yaml](https://github.com/falcosecurity/plugins/blob/master/plugins/k8saudit/rules/k8s_audit_rules.yaml) contains the list `eks_allowed_k8s_users` for whitelisting Kubernetes users that are specific and standard to Amazon EKS.

As of now the list is not complete (which it never will be), leading to warnings, when the rules are used without customization.

> 14:54:29.810991000: Warning K8s Operation performed by user not in allowed list of users (user=eks:cloud-controller-manager target=cloud-controller-manager/leases verb=get uri=/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cloud-controller-manager?timeout=5s resp=200)
> 14:54:29.969626000: Warning K8s Operation performed by user not in allowed list of users (user=eks:vpc-resource-controller target=cp-vpc-resource-controller/configmaps verb=get uri=/api/v1/namespaces/kube-system/configmaps/cp-vpc-resource-controller resp=200)

**Feature**

Add the two users to allowed_k8s_users

**Alternatives**

Users of rules to it themselves for example like this:

```yaml
- list: eks_allowed_k8s_users
  append: true
  items:
    # Used by official VPC CNI add-on for Amazon EKS.
    - eks:vpc-resource-controller
    # Used by official AWS cloud controller manager.
    - eks:cloud-controller-manager
```
