### ISSUE TITLE
falco-k8saudit: Pod getting OOM - Memory leak ?

### ISSUE THREAD

**Issue by Lowaiz** [falcosecurity/plugins#231]
**Describe the bug**

Few days back, I deployed, via the helm chart, falco with the k8saudit plugin, and once the kube-apiserver succeed to send its log to the pod, this one started to consume more and more memory until it hits the limit and get OOM killed.

**How to reproduce it**

Deploy Falco with k8s plugin and plug it as the audit webhook of the Kubernetes cluster

**Expected behaviour**

No leaks

**Screenshots**

![image](https://user-images.githubusercontent.com/43639116/214096268-faffb3c4-827b-42e5-b414-5afe24514739.png)

**Environment**

- Falco version: 0.33.1
- Installation method: Official Helm Chart
- Plugins: k8saudit, json

**Additional context**

Values used:
```
falco:
  selectLabels:
    - app.kubernetes.io/name: falco-audit
    - app.kubernetes.io/instance: falco-audit
  rules_file:
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config:
        ""
      open_params: "http://0.0.0.0:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  webserver:
    enabled: false
  http_output:
    enabled: true
    url: URL
  load_plugins: [ k8saudit, json ]
  libs_logger:
      enabled: true
  stdout_output:
      enabled: false
  json_output: true
  priority: error
```
