### ISSUE TITLE
Issue adding source IP and arn from EKS Cloudwatch logs

### ISSUE THREAD

**Issue by eranp22** [falcosecurity/plugins#239]
Hi,

I would like to suggest to automatically include the ARN and source IP address in the logs when it sends security events to CloudWatch. Additionally, If it possible change on existing rules for example to detect any attempt to attach/exec to a pod. The rule should meet the following conditions:

```
rule: Attach/Exec Pod
desc: >
Detect any attempt to attach/exec to a pod
condition: kevt_started and pod_subresource and kcreate and ka.target.subresource in (exec,attach) and not user_known_exec_pod_activities
output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresource command=%ka.uri.param[command])
priority: NOTICE
source: k8s_audit
tags: [k8s]
```
This is what I had tried
adding this:
`arn=%ka.user.extra[0]` I got the error

> LOAD_ERR_COMPILE_OUTPUT (Error compiling output): invalid formatting token ka.target.extra.arn[0])
For source IP I've trying to add:

`src_ip=%ka.target.sourceIPs` I got the error

> LOAD_ERR_COMPILE_OUTPUT (Error compiling output): invalid formatting token ka.target.sourceIPs)

Additional context

Currently, Falco sends logs to CloudWatch without including the ARN and source IP address. By automatically including this information in the logs, Falco can improve the efficiency and effectiveness of incident response. Additionally, the new rule or existing rules for detecting attempts to attach/exec to a pod will provide additional security visibility and help prevent potential security threats.

**Comment by Issif** [comment]
```json
    "sourceIPs": [
        "10.0.137.52"
    ]
```

I watched in Cloudwatch Logs, the `sourceIPs` is an array, so it make sense that `ka.sourceips` is null, try `ka.sourceips[0]` to be sure. If it's empty, then we really have an issue in the extraction.

For the ARN, it's too relative to AWS, as I said, you could extract it with the json extractor plugin, something like:
```
json.value[/user/extra/arn/0]
```

(I didn't test, it's just an example)

**Comment by eranp22** [comment]
Hi @Issif ,
I have try to change the output on rule to:
`output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresourresource command=%ka.uri.param[command] sourceIP=%ka.sourceips[0] arn=json.value[/user/extra/arn/0]`

This is the output that I've got

> 15:43:24.227917000: Notice Attach/Exec to pod (user=kubernetes-admin pod=falco-name resource=pods ns=falco action=exec command=/bin/bash sourceIP=<NA> arn=json.value[/user/extra/arn/0])

It seems that It's not working now.
Do you have any idea how can I find solution to resolve this?

**Comment by Issif** [comment]
I forgot the `%`, it's more something like:
```yaml
 output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresourresource command=%ka.uri.param[command] sourceIP=%ka.sourceips[0] arn=%json.value[/user/extra/arn/0]
```

**Comment by eranp22** [comment]
Hi @Issif 
It works with json.value 
`sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]`
Thank you very much.

**Comment by eranp22** [comment]
Hi @Issif 
I was wondering if you could assist me with modifying the k8s_audit_rules.yaml file to add these fields and apply the changes to every pod. I've tried creating a k8s_audit_rules_local.yaml file on my machine, but I'm not quite sure how to proceed.

What are the steps that I need to do it?

**Comment by eranp22** [comment]
any updates?

**Comment by Issif** [comment]
If you install Falco with Helm, you can override the rules you want with the values.yaml:
```yaml
customRules:
  override-k8saudit.yaml: |-
   - rule: Create Sensitive Mount Pod
     output:  output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresourresource command=%ka.uri.param[command] sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]]
```
You need to reproduce that for each rule you want to override.

**Comment by eranp22** [comment]
Hi @Issif 
Thanks for your quick response.

I have some issues, it's not working with this configuration:
```
falco:
  rules_file:
    - /etc/falco/k8s_audit_rules.yaml
  customRules:
  override-k8saudit.yaml: |-
   - rule: Attach/Exec Pod
     output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresourresource command=%ka.uri.param[command] sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]]
```
I want also to modify this list:
```
- list: eks_allowed_k8s_users
  items: [
    "eks:node-manager",
    "eks:certificate-controller",
    "eks:fargate-scheduler",
    "eks:k8s-metrics",
    "eks:authenticator",
    "eks:cluster-event-watcher",
    "eks:nodewatcher",
    "eks:pod-identity-mutating-webhook",
    "eks:cloud-controller-manager",
    "eks:vpc-resource-controller",
    "eks:addon-manager",
    "eks:cloud-controller-manager",
    "eks:vpc-resource-controller",
    ]
  
Do you have any recommendations on how to config this?

**Comment by eranp22** [comment]
Hi.
Thanks for your quick response.

So I change to this on the values file
```
customRules:
  override-k8saudit.yaml: |-
    - list: allowed_k8s_users
      append: true
      items: [eks:cloud-controller-manager, eks:vpc-resource-controller, eks:az-poller]
    - rule: Attach/Exec Pod
      output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresourresource command=%ka.uri.param[command] sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]]
```

But for the rules I've got error:

```
Error: /etc/falco/rules.d/override-k8saudit.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/rules.d/override-k8saudit.yaml:0:0)
    rule 'Attach/Exec Pod': (/etc/falco/rules.d/override-k8saudit.yaml:3:2)
- rule: Attach/Exec Pod
LOAD_ERR_YAML_VALIDATE (Error validating internal structure of YAML file): Item has no mapping for key 'condition'
```

**Comment by Issif** [comment]
Following this comment https://github.com/falcosecurity/falco/issues/2314#issuecomment-1345269904 from @jasondellaluce for rules we need to override everything, it's not pretty practical I agree.

```
customRules:
  override-k8saudit.yaml: |-
    - list: allowed_k8s_users
      append: true
      items: [eks:cloud-controller-manager, eks:vpc-resource-controller, eks:az-poller]
	- rule: Attach/Exec Pod
	  desc: >
	    Detect any attempt to attach/exec to a pod
	  condition: kevt_started and pod_subresource and kcreate and ka.target.subresource in (exec,attach) and not user_known_exec_pod_activities
	  output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresource command=%ka.uri.param[command]  sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
	  priority: NOTICE
	  source: k8s_audit
	  tags: [k8s]
```
