### ISSUE TITLE
Falco not triggering rules after disabling a default rule using customRules

### ISSUE THREAD

**Issue by eranp22** [falcosecurity/plugins#246]
Hi 

After I've disabled a default rule with this example [issue](https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L369,L375) using customRules in the Falco configuration.
```
customRules:
  override-k8saudit.yaml: |-
         - rule: Anonymous Request Allowed
            enabled: false
```
By the way this rule triggered more then 300 times in 15 minutes.
Do you know why?

The Falco logs show that the configuration file has been loaded successfully, and the rules have been loaded, but no events are being logged when manually triggered. The issue only occurs after disabling a default rule using the customRules property.
log from the pod (add 2h from GMT):
```
Sun Mar 26 14:30:59 2023: Falco version: 0.34.1 (x86_64)
Sun Mar 26 14:30:59 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Sun Mar 26 14:30:59 2023: Loading plugin 'k8saudit-eks' from file /usr/share/falco/plugins/libk8saudit-eks.so
Sun Mar 26 14:30:59 2023: Loading plugin 'json' from file /usr/share/falco/plugins/libjson.so
Sun Mar 26 14:30:59 2023: Loading rules from file /etc/falco/k8s_audit_rules.yaml
Sun Mar 26 14:30:59 2023: Loading rules from file /etc/falco/rules.d/override-k8saudit.yaml
Sun Mar 26 14:30:59 2023: Starting health webserver with threadiness 2, listening on port 8765
Sun Mar 26 14:30:59 2023: Enabled event sources: k8s_audit
Sun Mar 26 14:30:59 2023: Opening capture with plugin 'k8saudit-eks'
```
As you can see without any rule triggered like exec to pod
But when I deleted the Falco namespace all the events arrived of the triggered rules.

That was after I deleted the Falco namespace:
![image](https://user-images.githubusercontent.com/106144718/227785320-b14e471d-dfae-4cc1-93e9-e1b9642a4857.png)
Unix time:
1,679,841,117,794,301,952 - Sun Mar 26 2023 14:31:57 GMT
1,679,841,197,925,266,944 - Sun Mar 26 2023 14:33:17 GMT

Do you have any idea how can I find a solution to resolve this?

**Comment by Issif** [comment]
The condition of the rule `Anonymous Request Allowed` is:
```yaml
kevt and ka.user.name=system:anonymous and ka.auth.decision="allow" and not health_endpoint and not live_endpoint and not ready_endpoint
```

I think you notice a lot of events because the liveness/readiness endpoints that some pods use are different from the `live_endpoint` and `ready_enpoint` macros: [Source](https://github.com/falcosecurity/plugins/blob/master/plugins/k8saudit/rules/k8s_audit_rules.yaml#L150,L154)


> The Falco logs show that the configuration file has been loaded successfully, and the rules have been loaded, but no events are being logged when manually triggered. The issue only occurs after disabling a default rule using the customRules property.

For this issue, I'm sorry but can you explain a little bit more, I don't understand what you're expecting

**Comment by Issif** [comment]
I don't know if it's the Github formatting, but the indentation is wrong in your example, it should be
```yaml
customRules:
  override-k8saudit.yaml: |-
    - rule: Anonymous Request Allowed
      enabled: false
      condition: kevt and ka.user.name=system:anonymous and ka.auth.decision="allow" and not health_endpoint and not live_endpoint and not ready_endpoint
      desc: Detect any request made by the anonymous user that was allowed
      output: Request by anonymous user allowed (user=%ka.user.name verb=%ka.verb uri=%ka.uri 
      reason=%ka.auth.reason))
      priority: WARNING
      source: k8s_audit
      tags: [k8s]
```

I already answered why you got so many alerts with this rule, it was because of the probe endpoints.

Falco has a buffer mechanism, the logs are not flushed immediately by default and I guess you use fluentd/filebeat to collect them from stdout. Set `tty: true` https://github.com/falcosecurity/charts/blob/6fff4e1e75c43af742596f478bf86e7723aa08da/falco/values.yaml#L130 and you should get all the logs in real time in your stdout. My guess is the events were already buffered and you got them later, thinking it was relative to your immediate action of deletion of a namespace.

**Comment by eranp22** [comment]
Hi @Issif ,
Thanks for your quick response,


I've tried to add the value `tty: true`, it seems that it didn't help with the issue.
Yes, We are collecting the logs by fluentd.

These are the last logs from the Falco pod before I deleted it.
![image](https://user-images.githubusercontent.com/106144718/228870313-aa89e5c1-6b22-43aa-94d6-ff294ab58a1b.png)


After deleting the pod:
At 17:46 (UTC +3)
<img width="928" alt="image" src="https://user-images.githubusercontent.com/106144718/228876182-a18071d3-34e4-40cd-8ed6-93104bcef7b8.png">
These are the logs for the creation new pod after I got the events from old pod.
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/106144718/228876545-f45c0970-0e63-4ad0-892a-8d5ad2711b9b.png">

**Comment by Issif** [comment]
So you're noticing a latency between an action (like an exec into a pod) and the alert from Falco. I didn't noticed you use the `k8saudit-eks` plugin. When I developed it, I also noticed latencies from time to time. 

There were 2 causes:

- by the async nature of Cloudwatch Logs system, there might be a latency between the creation of the audit log and its availability for search
- if the instance size of the node running falco + the plugin is too small, there's really often a latency because the cpu cycles are not fast enough, consider to run at least a `xlarge` or `2x.large`

**Comment by eranp22** [comment]
Hi @Issif ,
I will check it later but I don't think this is the issue because when this config is executed we have no issues:
```
customRules:
  override-k8saudit.yaml: |-
    - list: allowed_k8s_users
      append: true
      items: [eks:cloud-controller-manager, eks:vpc-resource-controller, eks:az-poller, eks:addon-manager]
    - rule: Attach/Exec Pod
      desc: Detect any attempt to attach/exec to a pod
      condition: kevt_started and pod_subresource and kcreate and ka.target.subresource in (exec,attach) and not user_known_exec_pod_activities
      output: Attach/Exec to pod (user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresource command=%ka.uri.param[command] sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: NOTICE
      source: k8s_audit
      tags: [k8s]
    - rule: K8s Namespace Created
      desc: Detect any attempt to create a namespace
      condition: (kactivity and kcreate and namespace and response_successful)
      output: K8s Namespace Created (user=%ka.user.name namespace=%ka.target.name resource=%ka.target.resource resp=%ka.response.code decision=%ka.auth.decision reason=%ka.auth.reason sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: INFO
      source: k8s_audit
      tags: [k8s]
    - rule: K8s Namespace Deleted
      desc: Detect any attempt to delete a namespace
      condition: (kactivity and non_system_user and kdelete and namespace and response_successful)
      output: K8s Namespace Deleted (user=%ka.user.name namespace=%ka.target.name resource=%ka.target.resource resp=%ka.response.code decision=%ka.auth.decision reason=%ka.auth.reason sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: INFO
      source: k8s_audit
      tags: [k8s]
    - rule: Create Disallowed Namespace
      desc: Detect any attempt to create a namespace outside of a set of known namespaces
      condition: kevt and namespace and kcreate and not ka.target.name in (allowed_namespaces)
      output: Disallowed namespace created (user=%ka.user.name ns=%ka.target.name resource=%ka.target.resource sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: WARNING
      source: k8s_audit
      tags: [k8s]
    - rule: K8s Serviceaccount Created
      desc: Detect any attempt to create a service account
      condition: (kactivity and kcreate and serviceaccount and response_successful and not ka.user.name startswith "system")
      output: Ks Serviceaccount Created (user=%ka.user.name serviceaccount=%ka.target.name ns=%ka.target.namespace resource=%ka.target.resource resp=%ka.response.code decision=%ka.auth.decision reason=%ka.auth.reason sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: INFO
      source: k8s_audit
      tags: [k8s]
    - rule: Service Account Created in Kube Namespace
      desc: Detect any attempt to create a serviceaccount in the kube-system or kube-public namespaces
      condition: kevt and serviceaccount and kcreate and ka.target.namespace in (kube-system, kube-public) and response_successful and not trusted_sa and not ka.user.name startswith "system"
      output: Service account created in kube namespace (user=%ka.user.name serviceaccount=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: WARNING
      source: k8s_audit
      tags: [k8s]
    - rule: K8s Secret Created
      desc: Detect any attempt to create a secret. Service account tokens are excluded.
      condition: (kactivity and kcreate and secret and ka.target.namespace!=kube-system and non_system_user and response_successful)
      output: K8s Secret Created (user=%ka.user.name secret=%ka.target.name ns=%ka.target.namespace resource=%ka.target.resource resp=%ka.response.code decision=%ka.auth.decision reason=%ka.auth.reason sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: INFO
      source: k8s_audit
      tags: [k8s]
    - rule: K8s Secret Deleted
      desc: Detect any attempt to delete a secret. Service account tokens are excluded.
      condition: (kactivity and kdelete and secret and ka.target.namespace!=kube-system and non_system_user and response_successful)
      output: K8s Secret Deleted (user=%ka.user.name secret=%ka.target.name ns=%ka.target.namespace resource=%ka.target.resource resp=%ka.response.code decision=%ka.auth.decision reason=%ka.auth.reason sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: INFO
      source: k8s_audit
      tags: [k8s]
    - rule: K8s Secret Get Successfully
      desc: Detect any attempt to get a secret. Service account tokens are excluded.
      condition: secret and kget and kactivity and response_successful
      output: K8s Secret Get Successfully (user=%ka.user.name secret=%ka.target.name ns=%ka.target.namespace resource=%ka.target.resource resp=%ka.response.code decision=%ka.auth.decision reason=%ka.auth.reason sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: ERROR
      source: k8s_audit
      tags: [k8s]
    - rule: Create/Modify Configmap With Private Credentials
      desc: Detect creating/modifying a configmap containing a private credential (aws key, password, etc.)
      condition: kevt and configmap and kmodify and contains_private_credentials
      output: K8s configmap with private credential (user=%ka.user.name verb=%ka.verb resource=%ka.target.resource configmap=%ka.req.configmap.name config=%ka.req.configmap.obj sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: WARNING
      source: k8s_audit
      tags: [k8s]
    - rule: Create Privileged Pod
      desc: Detect an attempt to start a pod with a privileged container
      condition: kevt and pod and kcreate and ka.req.pod.containers.privileged intersects (true) and not ka.req.pod.containers.image.repository in (falco_privileged_images)
      output: Pod started with privileged container (user=%ka.user.name pod=%ka.resp.name resource=%ka.target.resource ns=%ka.target.namespace images=%ka.req.pod.containers.image sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: WARNING
      source: k8s_audit
      tags: [k8s]
    - rule: Create Disallowed Pod
      desc: Detect an attempt to start a pod with a container image outside of a list of allowed images.
      condition: kevt and pod and kcreate and not allowed_k8s_containers
      output: Pod started with container not in allowed list (user=%ka.user.name pod=%ka.resp.name ns=%ka.target.namespace images=%ka.req.pod.containers.image sourceIP=%json.value[/sourceIPs/0] arn=%json.value[/user/extra/arn/0]])
      priority: WARNING
      source: k8s_audit
      tags: [k8s]
```

But when I tried to disable the rule (Anonymous Request Allowed), we don't have any events triggered, the issue is not the latency, it's that after configuration and overwriting the rule above, I don't see any events triggered while manually triggered the events and after deleting the Falco pod or the Falco namespace all of the events that were supposed to trigger are triggered and sent, only after deletion.
