### ISSUE TITLE
k8saudit plugin can not output the change of configmap object

### ISSUE THREAD

**Issue by cui3093** [falcosecurity/plugins#249]
**Describe the bug**
The `ka.req.configmap.obj` field can not output any contents.

**How to reproduce it**

The rule as below

```yaml
    - rule: Not allowed configmap being changed
      desc: >
        Some body is changing a configmap that being not allowed
      condition: >
        kevt
        and configmap
        and not (ka.verb in (watch, list))
        and ka.req.configmap.name = "falco-k8s-audit-rules"
      output: >
        "Not allowed configmap changing happenned (user=%ka.user.name node=%ka.target.name verb=%ka.verb resource=%ka.target.resource configmap=%ka.req.configmap.name m_obj=%ka.req.configmap.obj)"
      priority: ERROR
      source: k8s_audit
      tag: [k8s]
```

**Expected behaviour**

The `ka.req.configmap.obj` filed should ouput the content after edited or before edited.

**Screenshots**
![image](https://user-images.githubusercontent.com/33884456/228456526-68af914a-b1b9-4737-b2c3-da1bd1effd1d.png)

**Environment**

- Falco version:

Falco version: 0.34.1 (x86_64)
- System info:
```json
{
  "machine": "x86_64",
  "nodename": "k8s-master001",
  "release": "5.14.0-162.12.1.el9_1.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP PREEMPT_DYNAMIC Mon Jan 23 14:51:52 EST 2023"
}
```
- Cloud provider or hardware configuration:
hardware configuration: vituralbox 7.0.6
- OS:
```shell
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.1 (Lime Lynx)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```
- Kernel:
```shell
Linux k8s-master001 5.14.0-162.12.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan 23 14:51:52 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

- Installation method:

Kubernetes

**Additional context**
