### ISSUE TITLE
K8smeta does not populate its events even though it is configured correctly and there are no errors

### ISSUE THREAD

**Issue by fjellvannet** [falcosecurity/plugins#514]
**Describe the bug**
I set up k8smeta and k8smetacollector according to this command (line 273 in [Falco's official Helm chart](https://github.com/falcosecurity/charts/blob/master/charts/falco/README.md?plain=1)):

```bash
helm install falco falcosecurity/falco \
    --namespace falco \
    --create-namespace \
    --set collectors.kubernetes.enabled=true
```

I create and add a custom syscall rule that often triggers in my deployment, and use a k8smeta-field, `k8smeta.pod.name` to be precise. I would expect this field to be populated, but it returns `N/A`. Sorry for this bug report being very long, I just included a lot of context :)

**How to reproduce it**

Deploy falco with the following command using its Helm-chart:
`helm upgrade --install falco falcosecurity/falco --namespace falco --create-namespace -f falco-values.yaml`

falco-values.yaml has the following contents:
```yaml
falco:
  rules_file:
    - /etc/falco/rules.d

driver:
  kind: ebpf

collectors:
  kubernetes:
    enabled: false

falcosidekick:
  enabled: true
  webui:
    enabled: true

customRules:
  rules-k8smeta.yaml: |-
    - macro: k8s_containers
      condition: >
        (container.image.repository in (gcr.io/google_containers/hyperkube-amd64,
        gcr.io/google_containers/kube2sky,
        docker.io/sysdig/sysdig, sysdig/sysdig,
        fluent/fluentd-kubernetes-daemonset, prom/prometheus,
        falco_containers,
        falco_no_driver_containers,
        ibm_cloud_containers,
        velero/velero,
        quay.io/jetstack/cert-manager-cainjector, weaveworks/kured,
        quay.io/prometheus-operator/prometheus-operator,
        registry.k8s.io/ingress-nginx/kube-webhook-certgen, quay.io/spotahome/redis-operator,
        registry.opensource.zalan.do/acid/postgres-operator, registry.opensource.zalan.do/acid/postgres-operator-ui,
        rabbitmqoperator/cluster-operator, quay.io/kubecost1/kubecost-cost-model,
        docker.io/bitnami/prometheus, docker.io/bitnami/kube-state-metrics, mcr.microsoft.com/oss/azure/aad-pod-identity/nmi)
        or (k8s.ns.name = "kube-system"))

    - macro: never_true
      condition: (evt.num=0)

    - macro: container
      condition: (container.id != host)

    - macro: k8s_api_server
      condition: (fd.sip.name="kubernetes.default.svc.cluster.local")
    
    - macro: user_known_contact_k8s_api_server_activities
      condition: (never_true)
    
    - rule: Custom Contact K8S API Server From Container
      desc: >
        Detect attempts to communicate with the K8S API Server from a container by non-profiled users. Kubernetes APIs play a 
        pivotal role in configuring the cluster management lifecycle. Detecting potential unauthorized access to the API server 
        is of utmost importance. Audit your complete infrastructure and pinpoint any potential machines from which the API server 
        might be accessible based on your network layout. If Falco can't operate on all these machines, consider analyzing the 
        Kubernetes audit logs (typically drained from control nodes, and Falco offers a k8saudit plugin) as an additional data 
        source for detections within the control plane.
      condition: >
        evt.type=connect and evt.dir=< 
        and (fd.typechar=4 or fd.typechar=6) 
        and container 
        and k8s_api_server 
        and not k8s_containers 
        and not user_known_contact_k8s_api_server_activities
      output: Custom Unexpected connection to K8s API Server from container (connection=%fd.name lport=%fd.lport rport=%fd.rport fd_type=%fd.type fd_proto=%fd.l4proto evt_type=%evt.type user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline k8s_podname=%k8smeta.pod.name orig_podname=%k8s.pod.name terminal=%proc.tty %container.info)
      priority: NOTICE
      tags: [maturity_stable, container, network, k8s, mitre_discovery, T1565]
```

The included custom rule is a copy of the `Custom Contact K8S API Server From Container` rule with all its dependencies. The only modification is that two new fields `k8s_podname=%k8smeta.pod.name` and `orig_podname=%k8s.pod.name` are added to the output. The `orig_podname` field is populated - it says the same as `k8s.pod.name` in the output. However, `k8s_podname` remains `N/A`, and I would expect this field to be populated if the same value is available in `k8s.pod.name`, which is said to only be kept alive for backwards compatibility purposes (line 250 in [Falco's official Helm chart](https://github.com/falcosecurity/charts/blob/master/charts/falco/README.md?plain=1)).

**Expected behaviour**
I would expect that if `k8s.pod.name` is populated with a value, `k8smeta.pod.name` should also be populated.

**Screenshots**
![k8smeta-fields not available](https://github.com/falcosecurity/plugins/assets/22413504/eea5989e-856c-463f-9f0c-eee1caa85213)
Checking out the events in the UI, we see that the k8s_podname field remains `N/A` while orig_podname gets the same value as k8s.pod.name. 

![metacollector is running](https://github.com/falcosecurity/plugins/assets/22413504/6a585ec1-74ea-46e6-800c-3c490bfa71bf)
falco-k8s-metacollector is running in the same namespace as the falco-pods and the UI.

![k8smeta plugin is installed](https://github.com/falcosecurity/plugins/assets/22413504/c7e44126-10b6-40dd-98f3-8bd78c8ef0ec)
Logs from the artifact-install-container show that k8smeta is indeed installed correctly.

**Environment**

- Falco version: 0.38.1 (x86_64)

- System info: {"machine":"x86_64","nodename":"falco-fq2mk","release":"6.8.0-36-generic","sysname":"Linux","version":"\#36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024"},"version":"0.38.1"}

- Cloud provider or hardware configuration: microk8s on three VM's which are connected in a cluster, each with 4 vCPU's and 16 GB RAM. microk8s uses its own version of containerd that has its socket in `/var/snap/microk8s/common/run/containerd.sock`. In that position falco does not find it, so I created an empty file in `/run/containerd/containerd.sock`, and then used `sudo mount --bind /var/snap/microk8s/common/run/containerd.sock /run/containerd/containerd.sock` to make it accessible for falco. That seems to work, as before this change the pod- and containername were `N/A` in the UI as well, and now they are populated, so falco seems to have access to the containerd socket at least. Changing the deployment volume `containerd-socket` to mount the `/var/snap/microk8s/common/run` to falco instead of `/run/containerd` also works.
- OS: Ubuntu
```
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

- Kernel: `Linux microk8s-1 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

- Installation method:
`helm upgrade --install falco falcosecurity/falco --namespace falco --create-namespace -f falco-values.yaml`, see above.

**Additional context**
`/etc/falco/falco.yaml` pulled from one of the falco-pods:

```
base_syscalls:
  custom_set: []
  repair: false
buffered_outputs: false
config_files:
- /etc/falco/config.d
engine:
  ebpf:
    buf_size_preset: 4
    drop_failed_exit: false
    probe: ${HOME}/.falco/falco-bpf.o
  kind: ebpf
falco_libs:
  thread_table_size: 262144
file_output:
  enabled: false
  filename: ./events.txt
  keep_alive: false
grpc:
  bind_address: unix:///run/falco/falco.sock
  enabled: false
  threadiness: 0
grpc_output:
  enabled: false
http_output:
  ca_bundle: ""
  ca_cert: ""
  ca_path: /etc/falco/certs/
  client_cert: /etc/falco/certs/client/client.crt
  client_key: /etc/falco/certs/client/client.key
  compress_uploads: false
  echo: false
  enabled: true
  insecure: false
  keep_alive: false
  mtls: false
  url: http://falco-falcosidekick:2801
  user_agent: falcosecurity/falco
json_include_output_property: true
json_include_tags_property: true
json_output: true
libs_logger:
  enabled: false
  severity: debug
load_plugins:
- k8smeta
log_level: info
log_stderr: true
log_syslog: true
metrics:
  convert_memory_to_mb: true
  enabled: false
  include_empty_values: false
  interval: 1h
  kernel_event_counters_enabled: true
  libbpf_stats_enabled: true
  output_rule: true
  resource_utilization_enabled: true
  rules_counters_enabled: true
  state_counters_enabled: true
output_timeout: 2000
outputs:
  max_burst: 1000
  rate: 0
outputs_queue:
  capacity: 0
plugins:
- init_config: null
  library_path: libk8saudit.so
  name: k8saudit
  open_params: http://:9765/k8s-audit
- library_path: libcloudtrail.so
  name: cloudtrail
- init_config: ""
  library_path: libjson.so
  name: json
- init_config:
    collectorHostname: falco-k8s-metacollector.falco.svc
    collectorPort: 45000
    nodeName: ${FALCO_K8S_NODE_NAME}
  library_path: libk8smeta.so
  name: k8smeta
priority: debug
program_output:
  enabled: false
  keep_alive: false
  program: 'jq ''{text: .output}'' | curl -d @- -X POST https://hooks.slack.com/services/XXX'
rule_matching: first
rules_file:
- /etc/falco/rules.d
stdout_output:
  enabled: true
syscall_event_drops:
  actions:
  - log
  - alert
  max_burst: 1
  rate: 0.03333
  simulate_drops: false
  threshold: 0.1
syscall_event_timeouts:
  max_consecutives: 1000
syslog_output:
  enabled: true
time_format_iso_8601: false
watch_config_files: true
webserver:
  enabled: true
  k8s_healthz_endpoint: /healthz
  listen_port: 8765
  prometheus_metrics_enabled: false
  ssl_certificate: /etc/falco/falco.pem
  ssl_enabled: false
  threadiness: 0
```
As far as I can see, k8smeta and k8smeta collector are configured correctly here in the config as well. I experimented with changing the port or hostname of the metacollector, and then I got errors, same when I turned on SSL without fixing the certificates. This screenshot from the falco-container log also confirms that k8smeta is running - it says that it received at least one event from k8s-metacollector, indicating that their connection should be OK.

![k8smeta plugin is healthy - no errors in logs](https://github.com/falcosecurity/plugins/assets/22413504/2052c375-b570-4438-a62c-dd06e4199948)
Also here it looks as if the k8smeta plugin is healthy. When I removed `collectors.kubernetes.enabled=true`, falco would not start any longer claiming that I used an invalid value in my rule in `rules-k8smeta.yaml`, the invalid value being `k8smeta.pod.name`, which is another indication of `k8smeta` likely being set up correctly.
