### ISSUE TITLE
Container plugin: can't use only containerd engine without enabling cri

### ISSUE THREAD

**Issue by wangwillian0** [falcosecurity/plugins#850]
The following configuration doesn't work as expected. I need to enable the cri engine with the containerd at the same time, even though the crio.sock is not mounted. 

As experiment, enabling only the cri engine and disabling the containerd doesn't work.

```
  - init_config:
      engines:
        bpm:
          enabled: false
        containerd:
          enabled: true
          sockets:
            - /run/containerd/containerd.sock
        cri:
          enabled: false
          sockets:
            - /run/crio/crio.sock
        docker:
          enabled: false
          sockets:
            - /var/run/docker.sock
        libvirt_lxc:
          enabled: false
        lxc:
          enabled: false
        podman:
          enabled: false
          sockets:
            - /run/podman/podman.sock
      hooks:
        - create
      label_max_len: 100
      with_size: false
    library_path: libcontainer.so
    name: container
```
